-- @description Hardware recording manager
-- @author Simon Goričar
-- @about
--   A script for managing monitoring and recording MIDI and audio data from your
--   hardware devices (synths, etc.). You register a list of instruments that exist as
--   track structures; then you can easily enable or disable MIDI IN/OUT/THROUGH and AUDIO IN
--   paths for quick monitoring and recording.
-- @link https://github.com/DefaultSimon/simong_reaper-scripts
-- @version 0.1.1
-- @changelog
--  - Fix dependencies and internal library not being included in the script package.
-- @metapackage
-- @provides
--   [main=main] hardware-recording-manager/simong_hardware-recording-manager.lua
--   [nomain] hardware-recording-manager/external_libraries/*.lua
--   [nomain] hardware-recording-manager/internals/**/*.lua
